version: "3.8"
services:
    db:
        image: mysql:8.0
        env_file: .env.local
        environment:
            MYSQL_ROOT_PASSWORD: shopware
            MYSQL_USER: shopware
            MYSQL_PASSWORD: shopware
            MYSQL_DATABASE: shopware
        volumes:
          - ./data/db:/var/lib/mysql

    init-perm:
        image: alpine
        volumes:
            - ./data/app/files:/var/www/html/files
            - ./data/app/theme:/var/www/html/public/theme
            - ./data/app/media:/var/www/html/public/media
            - ./data/app/thumbnail:/var/www/html/public/thumbnail
            - ./data/app/sitemap:/var/www/html/public/sitemap
        command: chown 82:82 /var/www/html/files /var/www/html/public/theme /var/www/html/public/media /var/www/html/public/thumbnail /var/www/html/public/sitemap    

    init:
        image: local
        build:
            context: .
            dockerfile: docker/Dockerfile
        env_file: .app.env
        entrypoint: /setup
        volumes:
            - ./data/app/files:/var/www/html/files
            - ./data/app/theme:/var/www/html/public/theme
            - ./data/app/media:/var/www/html/public/media
            - ./data/app/thumbnail:/var/www/html/public/thumbnail
            - ./data/app/sitemap:/var/www/html/public/sitemap
        depends_on:
            db:
                condition: service_started
            init-perm:
                condition: service_completed_successfully
    web:
        image: local
        build:
            context: .
            dockerfile: docker/Dockerfile
        env_file: .app.env
        volumes:
            - ./data/app/files:/var/www/html/files
            - ./data/app/theme:/var/www/html/public/theme
            - ./data/app/media:/var/www/html/public/media
            - ./data/app/thumbnail:/var/www/html/public/thumbnail
            - ./data/app/sitemap:/var/www/html/public/sitemap
        depends_on:
            init:
                condition: service_completed_successfully
        ports:
            - 8089:8000      

    worker:
        image: local
        build:
            context: .
            dockerfile: docker/Dockerfile
        env_file: .app.env
        restart: unless-stopped
        volumes:
            - ./data/app/files:/var/www/html/files
            - ./data/app/theme:/var/www/html/public/theme
            - ./data/app/media:/var/www/html/public/media
            - ./data/app/thumbnail:/var/www/html/public/thumbnail
            - ./data/app/sitemap:/var/www/html/public/sitemap
        depends_on:
            init:
                condition: service_completed_successfully
        entrypoint: [ "php", "bin/console", "messenger:consume", "async", "low_priority", "--time-limit=300", "--memory-limit=512M" ]
        deploy:
            replicas: 1
         

    scheduler:
        image: local
        build:
            context: .
            dockerfile: docker/Dockerfile
        env_file: .app.env

        restart: unless-stopped

        volumes:
            - ./data/app/files:/var/www/html/files
            - ./data/app/theme:/var/www/html/public/theme
            - ./data/app/media:/var/www/html/public/media
            - ./data/app/thumbnail:/var/www/html/public/thumbnail
            - ./data/app/sitemap:/var/www/html/public/sitemap
        depends_on:
            init:
                condition: service_completed_successfully
        entrypoint: [ "php", "bin/console", "scheduled-task:run" ]
         
